Description of EOBAdiabLSO
Home > EOB > EOBAdiabLSO.m
EOBAdiabLSO
PURPOSE
EOBAdiabLSO Compute Last-Stable-Orbit (LSO) in the EOB formalism.
SYNOPSIS
function LSO = EOBAdiabLSO(nu, EOBopt)
DESCRIPTION
EOBAdiabLSO Compute Last-Stable-Orbit (LSO) in the EOB formalism.
   LSO = EOBAdiabLSO( nu, EOBopts ) return a structure with LSO data
CROSS-REFERENCE INFORMATION
This function calls:
EOBMetric EOBMetric Computes the EOB metric potentials and derivatives.
EOBOmgE EOBOmgE Computes Energy and orbital frequency along dynamics.
EOBfLSO EOBfLSO Compute function for adiabatic LSO determination.
This function is called by:
EOBRun
EOBRun_DIN_mod
EOBRun_insplunge_ringdown
SOURCE CODE
function LSO = EOBAdiabLSO(nu, EOBopt)
%EOBAdiabLSO Compute Last-Stable-Orbit (LSO) in the EOB formalism.
%
%   LSO = EOBAdiabLSO(nu, EOBopts) return a structure with LSO data
%
% LSO
LSO.u = fzero(@(x) EOBfLSO(x, nu, EOBopt), 1/5.7);
LSO.r = 1./LSO.u;
% Metric potentials
Metric = EOBMetric(nu, LSO.r, EOBopt);
A      = Metric.A;
dA     = Metric.dA;
% Angular momentum
j2    = LSO.r.^3.*dA./(2*A-LSO.r.*dA);
LSO.j = sqrt(j2);
LSO.Omega = EOBOmgE(nu, LSO.r,LSO.j,0, EOBopt, Metric);
LSO.w22   = 2*LSO.Omega;
% Newtonian-like connection
LSO.Newt_w22   = 2*LSO.u^(3/2);
LSO.Newt_Omega = LSO.u.^(3/2);