Description of EOBFluxHorizonFitCoefs
Home > EOB > EOBFluxHorizonFitCoefs.m
EOBFluxHorizonFitCoefs
PURPOSE
EOBFluxHorizonFitCoefs Coefficients for hybrid expression of rho_lm22 at the horizon.
SYNOPSIS
function c = EOBFluxHorizonFitCoefs(nu, EOBopt)
DESCRIPTION
EOBFluxHorizonFitCoefs Coefficients for hybrid expression of rho_lm22 at the horizon.
    c = EOBFluxHorizonFitCoefs(nu, EOBopt)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EOBRun
EOBRun_DIN_mod
EOBRun_insplunge_ringdown
SOURCE CODE
function c = EOBFluxHorizonFitCoefs(nu, EOBopt)
%EOBFluxHorizonFitCoefs Coefficients for hybrid expression of rho_lm22 at the horizon.
%
%    c = EOBFluxHorizonFitCoefs(nu, EOBopt)
%
LM2K = EOBopt.LM2K;
L    = EOBopt.L;
% Shorthands
k22 = LM2K(2,2);
k21 = LM2K(2,1);
k33 = LM2K(3,3);
k32 = LM2K(3,2);
k31 = LM2K(3,1);
k44 = LM2K(4,4);
k43 = LM2K(4,3);
k42 = LM2K(4,2);
k41 = LM2K(4,1);
nu2 = nu.^2;
nu3 = nu.^3;
% Allocate memory
kmax = length(L);
c{1} = zeros(kmax,1);
c{2} = c{1};
c{3} = c{1};
c{4} = c{1};
% l=2 ---------------------------------------------------------------
c{1}(k22) = (4-21*nu + 27*nu2 - 8*nu3)/(4*(1-4*nu+2*nu2));
c{2}(k22) =  4.78752;
c{3}(k22) = 26.760136;
c{4}(k22) = 43.861478;
c{1}(k21) = 0.58121;
c{2}(k21) = 1.01059;
c{3}(k21) = 7.955729;
c{4}(k21) = 1.650228;
% l=3 ---------------------------------------------------------------
c{1}(k33) = 1.13649;
c{2}(k33) = 3.84104;
c{3}(k33) = 45.696716;
c{4}(k33) = 27.955066;
c{1}(k32) =  0.83711;
c{2}(k32) =  1.39699;
c{3}(k32) =  23.638062;
c{4}(k32) =  -1.491898;
c{1}(k31) = 1.61064;
c{2}(k31) = 2.97176;
c{3}(k31) = 10.045280;
c{4}(k31) = 15.146875;
% l=4 ---------------------------------------------------------------
c{1}(k44) = 1.15290;
c{2}(k44) = 4.59627;
c{3}(k44) = 55.268737;
c{4}(k44) = 13.255971;
c{1}(k43) =  0.96063;
c{2}(k43) =  1.45472;
c{3}(k43) =  43.480636;
c{4}(k43) = -35.225828;
c{1}(k42) =  1.43458;
c{2}(k42) =  2.43232;
c{3}(k42) =  21.927986;
c{4}(k42) =  10.419841;
c{1}(k41) =  0.90588;
c{2}(k41) =  1.17477;
c{3}(k41) =  5.126480;
c{4}(k41) =  4.022307;