Description of EOBf22Pade
Home > EOB > EOBf22Pade.m
EOBf22Pade
PURPOSE
EOBf22Pade Computes the f22(x,nu) correction factor.
SYNOPSIS
function f22 = EOBf22Pade(x,nu)
DESCRIPTION
EOBf22Pade Computes the f22(x,nu) correction factor.
   f_22(x,nu) is computed up to 5PN, although the nu-dependent terms are
   included only up to 3PN
   f22 = EOBf22Pade(x,nu)
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EOBFluxDIN EOBFluxDIN Computes the resummed Newton-normalized GW energy flux.
EOBFluxDIN_mod EOBFluxDIN Computes the resummed Newton-normalized GW energy flux.
EOBhlm EOBhlm Compute the multipolar resummed waveform.
SOURCE CODE
function f22 = EOBf22Pade(x,nu)
%EOBf22Pade Computes the f22(x,nu) correction factor.
%   f_22(x,nu) is computed up to 5PN, although the nu-dependent terms are
%   included only up to 3PN
%
%   f22 = EOBf22Pade(x,nu)
%
EulerGamma =  0.577215664901533;
f22 =  (1 + x.*(-2.0476190476190474 + (55*nu)/42. + (16*(22823192996333290672 + 4438814994971806750*nu - 6823403945816406550*nu^2 + ...
                648967245910163250*nu^3 + 241275871566870525*nu*pi^2 - 16202595734063101440*(EulerGamma + 2*log(2) + log(x)/2.) + ...
                 1108298510258940000*nu*(EulerGamma + 2*log(2) + log(x)/2.) + 3031782946628436000*nu^2*(EulerGamma + 2*log(2) + log(x)/2.) - ...
                 399140081400060000*nu^3*(EulerGamma + 2*log(2) + log(x)/2.) - 148394039335542000*nu*pi^2*(EulerGamma + 2*log(2) + log(x)/2.) + ...
                2832619878382694400*(EulerGamma + 2*log(2) + log(x)/2.).^2))./ ...
                (21.*(12532505384160238848 - 10670479012368624000*nu - 4424104031641493100*nu^2 + 3108518854182651000*nu^3 + 402909426379687500*nu^4 - ...
                 249600015721875000*nu^5 + 20927334285812500*nu^6 + 398914528155343200*nu*pi^2 - 126902837624062500*nu^2*pi^2 - ...
                 92797381864687500*nu^3*pi^2 + 15560911128262500*nu^4*pi^2 + 2892651685048125*nu^2*pi^4 - ...
                 6863909635248906240*(EulerGamma + 2*log(2) + log(x)/2.) + 3603343665841920000*nu*(EulerGamma + 2*log(2) + log(x)/2.) + ...
                 1412960863362048000*nu^2*(EulerGamma + 2*log(2) + log(x)/2.) - 297034479181440000*nu^3*(EulerGamma + 2*log(2) + log(x)/2.) - ...
                 110432773459008000*nu*pi^2*(EulerGamma + 2*log(2) + log(x)/2.) + 1053998094281932800*(EulerGamma + 2*log(2) + log(x)/2.).^2))) + ...
                 x.^3.*(29.448714354428642 - (34625*nu)/3696. - (227875*nu^2)/33264. + (114635*nu^3)/99792. + (41*nu*pi^2)/96. - ...
                ((2.0476190476190474 - (55*nu)/42.)*((27.14132609139412 - (36808*(EulerGamma + 2*log(2) + log(x)/2.))/2205.).* ...
                (-27.14132609139412 + (36808*(EulerGamma + 2*log(2) + log(x)/2.))/2205.) - ...
                (-29.448714354428642 + (34625*nu)/3696. + (227875*nu^2)/33264. - (114635*nu^3)/99792. - (41*nu*pi^2)/96. + ...
                (856*(EulerGamma + 2*log(2) + log(x)/2.))/105.).*(-104.80215051710138 + (458816*(EulerGamma + 2*log(2) + log(x)/2.))/19845.)))./ ...
                ((2.835978835978836 + (6745*nu)/1512. - (2047*nu^2)/1512.)*(27.14132609139412 - (36808*(EulerGamma + 2*log(2) + log(x)/2.))/2205.) - ...
                (-29.448714354428642 + (34625*nu)/3696. + (227875*nu^2)/33264. - (114635*nu^3)/99792. - (41*nu*pi^2)/96. + ...
                (856*(EulerGamma + 2*log(2) + log(x)/2.))/105.).^2) - ...
                (16*(2.835978835978836 + (6745*nu)/1512. - (2047*nu^2)/1512.)* ...
                (22823192996333290672 + 4438814994971806750*nu - 6823403945816406550*nu^2 + 648967245910163250*nu^3 + 241275871566870525*nu*pi^2 - ...
                16202595734063101440*(EulerGamma + 2*log(2) + log(x)/2.) + 1108298510258940000*nu*(EulerGamma + 2*log(2) + log(x)/2.) + ...
                3031782946628436000*nu^2*(EulerGamma + 2*log(2) + log(x)/2.) - 399140081400060000*nu^3*(EulerGamma + 2*log(2) + log(x)/2.) - ...
                148394039335542000*nu*pi^2*(EulerGamma + 2*log(2) + log(x)/2.) + 2832619878382694400*(EulerGamma + 2*log(2) + log(x)/2.).^2))./ ...
               (21.*(12532505384160238848 - 10670479012368624000*nu - 4424104031641493100*nu^2 + 3108518854182651000*nu^3 + 402909426379687500*nu^4 - ...
                249600015721875000*nu^5 + 20927334285812500*nu^6 + 398914528155343200*nu*pi^2 - 126902837624062500*nu^2*pi^2 - ...
                92797381864687500*nu^3*pi^2 + 15560911128262500*nu^4*pi^2 + 2892651685048125*nu^2*pi^4 - ...
                6863909635248906240*(EulerGamma + 2*log(2) + log(x)/2.) + 3603343665841920000*nu*(EulerGamma + 2*log(2) + log(x)/2.) + ...
                1412960863362048000*nu^2*(EulerGamma + 2*log(2) + log(x)/2.) - 297034479181440000*nu^3*(EulerGamma + 2*log(2) + log(x)/2.) - ...
                110432773459008000*nu*pi^2*(EulerGamma + 2*log(2) + log(x)/2.) + 1053998094281932800*(EulerGamma + 2*log(2) + log(x)/2.).^2)) - ...
               (856*(EulerGamma + 2*log(2) + log(x)/2.))/105.) + (x.^2.* ...
               (-1447584473561717268037632 - 3490691432750957078592000*nu + 11117775993495292068170496*nu^2 - 1298465012873268136669500*nu^3 - ...
               2800230414735340569773700*nu^4 + 429137698170662791264500*nu^5 + 220089987610738990062500*nu^6 - 59339835276583992812500*nu^7 + ...
               3898281048758295062500*nu^8 - 109784167761318216566400*nu*pi^2 - 162210888696798713772000*nu^2*pi^2 + ...
               188411209563310287453900*nu^3*pi^2 + 27247497108001320150000*nu^4*pi^2 - 26837227347580274625000*nu^5*pi^2 + ...
               2898639842239353712500*nu^6*pi^2 - 1128735828719258760000*nu^2*pi^4 - 1775495141024113884375*nu^3*pi^4 + ...
               538834477935709580625*nu^4*pi^4 + 829132415453875222609920*(EulerGamma + 2*log(2) + log(x)/2.) + ...
               817401632289328383897600*nu*(EulerGamma + 2*log(2) + log(x)/2.) - 4194694629872685326868480*nu^2*(EulerGamma + 2*log(2) + log(x)/2.) + ...
               363785326167105722880000*nu^3*(EulerGamma + 2*log(2) + log(x)/2.) + 390726438519063943296000*nu^4*(EulerGamma + 2*log(2) + log(x)/2.) - ...
               55330691678481098880000*nu^5*(EulerGamma + 2*log(2) + log(x)/2.) + 53399546740556400384000*nu*pi^2*(EulerGamma + 2*log(2) + log(x)/2.) + ...
               47411550465288609600000*nu^2*pi^2*(EulerGamma + 2*log(2) + log(x)/2.) - ...
               20571085741623633216000*nu^3*pi^2*(EulerGamma + 2*log(2) + log(x)/2.) - 258076703375402655744000*nu*(EulerGamma + 2*log(2) + log(x)/2.).^2 + ...
               196335603008555596185600*nu^2*(EulerGamma + 2*log(2) + log(x)/2.).^2))./ ...
              (137592.*(12532505384160238848 - 10670479012368624000*nu - 4424104031641493100*nu^2 + 3108518854182651000*nu^3 + 402909426379687500*nu^4 - ...
               249600015721875000*nu^5 + 20927334285812500*nu^6 + 398914528155343200*nu*pi^2 - 126902837624062500*nu^2*pi^2 - ...
               92797381864687500*nu^3*pi^2 + 15560911128262500*nu^4*pi^2 + 2892651685048125*nu^2*pi^4 - ...
               6863909635248906240*(EulerGamma + 2*log(2) + log(x)/2.) + 3603343665841920000*nu*(EulerGamma + 2*log(2) + log(x)/2.) + ...
               1412960863362048000*nu^2*(EulerGamma + 2*log(2) + log(x)/2.) - 297034479181440000*nu^3*(EulerGamma + 2*log(2) + log(x)/2.) - ...
               110432773459008000*nu*pi^2*(EulerGamma + 2*log(2) + log(x)/2.) + 1053998094281932800*(EulerGamma + 2*log(2) + log(x)/2.).^2)))./ ...
               (1 + (x.^2.*((27.14132609139412 - (36808*(EulerGamma + 2*log(2) + log(x)/2.))/2205.).* ...
                (-27.14132609139412 + (36808*(EulerGamma + 2*log(2) + log(x)/2.))/2205.) - ...
               (-29.448714354428642 + (34625*nu)/3696. + (227875*nu^2)/33264. - (114635*nu^3)/99792. - (41*nu*pi^2)/96. + ...
               (856*(EulerGamma + 2*log(2) + log(x)/2.))/105.).*(-104.80215051710138 + (458816*(EulerGamma + 2*log(2) + log(x)/2.))/19845.)))./ ...
               ((2.835978835978836 + (6745*nu)/1512. - (2047*nu^2)/1512.)*(27.14132609139412 - (36808*(EulerGamma + 2*log(2) + log(x)/2.))/2205.) - ...
               (-29.448714354428642 + (34625*nu)/3696. + (227875*nu^2)/33264. - (114635*nu^3)/99792. - (41*nu*pi^2)/96. + ...
               (856*(EulerGamma + 2*log(2) + log(x)/2.))/105.).^2) + ...
               (16*x.*(22823192996333290672 + 4438814994971806750*nu - 6823403945816406550*nu^2 + 648967245910163250*nu^3 + 241275871566870525*nu*pi^2 - ...
               16202595734063101440*(EulerGamma + 2*log(2) + log(x)/2.) + 1108298510258940000*nu*(EulerGamma + 2*log(2) + log(x)/2.) + ...
               3031782946628436000*nu^2*(EulerGamma + 2*log(2) + log(x)/2.) - 399140081400060000*nu^3*(EulerGamma + 2*log(2) + log(x)/2.) - ...
               148394039335542000*nu*pi^2*(EulerGamma + 2*log(2) + log(x)/2.) + 2832619878382694400*(EulerGamma + 2*log(2) + log(x)/2.).^2))./ ...
               (21.*(12532505384160238848 - 10670479012368624000*nu - 4424104031641493100*nu^2 + 3108518854182651000*nu^3 + 402909426379687500*nu^4 - ...
               249600015721875000*nu^5 + 20927334285812500*nu^6 + 398914528155343200*nu*pi^2 - 126902837624062500*nu^2*pi^2 - ...
               92797381864687500*nu^3*pi^2 + 15560911128262500*nu^4*pi^2 + 2892651685048125*nu^2*pi^4 - ...
               6863909635248906240*(EulerGamma + 2*log(2) + log(x)/2.) + 3603343665841920000*nu*(EulerGamma + 2*log(2) + log(x)/2.) + ...
               1412960863362048000*nu^2*(EulerGamma + 2*log(2) + log(x)/2.) - 297034479181440000*nu^3*(EulerGamma + 2*log(2) + log(x)/2.) - ...
               110432773459008000*nu*pi^2*(EulerGamma + 2*log(2) + log(x)/2.) + 1053998094281932800*(EulerGamma + 2*log(2) + log(x)/2.).^2)));