Description of EOBNQCabFit
Home > EOB > EOBNQCabFit.m
EOBNQCabFit
PURPOSE
EOBNQCabFit Coefficients for NQC as fitted function of nu.
SYNOPSIS
function [a,b] = EOBNQCabFit(nu, EOBopt)
DESCRIPTION
EOBNQCabFit Coefficients for NQC as fitted function of nu.
   [a,b] = EOBInitNQCFit(nu, EOBopt )
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EOBRun
EOBRun_DIN_mod
EOBRun_insplunge_ringdown
SOURCE CODE
function [a,b] = EOBNQCabFit(nu, EOBopt)
%EOBNQCabFit Coefficients for NQC as fitted function of nu.
%
%   [a,b] = EOBInitNQCFit(nu, EOBopt)
%
L    = EOBopt.L;
LM2K = EOBopt.LM2K;
% Shorthands
k22 = LM2K(2,2);
k21 = LM2K(2,1);
k33 = LM2K(3,3);
k32 = LM2K(3,2);
%{
k31 = LM2K(3,1);
k44 = LM2K(4,4);
k43 = LM2K(4,3);
k42 = LM2K(4,2);
k41 = LM2K(4,1);
%}
nu2 = nu.^2;
% Allocate memory
kmax = length(L);
a{1} = zeros(kmax,1);
a{2} = a{1};
a{3} = a{1};
b{1} = a{1};
b{2} = a{1};
b{3} = a{1};
% l=2 -------------------------------------------------------------------
a{1}(k22) = +2.160054e+00*nu2 - 1.093667e+00*nu + 7.926107e-02;
a{2}(k22) = -1.080736e+01*nu2 + 7.141956e+00*nu + 7.034821e-01;
a{3}(k22) = -2.766573e+00*nu2 - 1.768795e-01*nu + 1.012170e-01;
b{1}(k22) = -8.568345e-01*nu2 - 2.416766e-01*nu + 1.928716e-01;
b{2}(k22) = +9.638222e+00*nu2 - 7.645317e+00*nu + 3.731762e-01;
b{3}(k22) = -8.099188e+01*nu2 + 1.707519e+01*nu - 1.797447e+00;
a{1}(k21) = +9.150277e-01*nu2 - 6.521591e-01*nu + 3.400123e-02;
a{2}(k21) = +1.903505e+00*nu2 + 4.978512e+00*nu - 7.105946e-01;
a{3}(k21) = +2.694953e+00*nu2 - 3.160287e+00*nu + 8.650109e-01;
b{1}(k21) = -2.247953e+00*nu2 + 5.304017e-01*nu + 2.465944e-01;
b{2}(k21) = +5.172595e+01*nu2 - 2.168939e+01*nu + 3.161619e+00;
b{3}(k21) = -1.128189e+02*nu2 + 3.055883e+01*nu - 2.607237e-03;
% l=3 -------------------------------------------------------------------
a{1}(k33) = +2.679308e+00*nu2 - 1.279163e+00*nu + 1.456279e-01;
a{2}(k33) = -1.293179e+01*nu2 + 1.063361e+01*nu + 4.704239e-01;
a{3}(k33) = -8.931901e-01*nu2 - 2.922908e+00*nu + 5.078229e-01;
b{1}(k33) = -1.646809e+00*nu2 - 1.611205e-01*nu + 3.464108e-01;
b{2}(k33) = +6.959682e+00*nu2 - 7.595824e+00*nu + 7.089351e-02;
b{3}(k33) = -2.134623e+02*nu2 + 5.281861e+01*nu - 3.471809e+00;
a{1}(k32) = +3.167065e+01*nu2 - 1.030991e+01*nu + 6.843778e-01;
a{2}(k32) = -1.327286e+02*nu2 + 5.515306e+01*nu - 3.044906e+00;
a{3}(k32) = -1.973440e+01*nu2 + 1.829857e+00*nu + 3.039708e-01;
b{1}(k32) = -1.349680e+00*nu2 - 1.808295e+00*nu + 5.734632e-01;
b{2}(k32) = -4.486021e+00*nu2 - 7.796816e+00*nu + 3.253824e+00;
b{3}(k32) = +3.248901e+00*nu2 - 3.813272e+01*nu + 6.164847e+00;
return