Description of EOBRRPN
Home > EOB > EOBRRPN.m
EOBRRPN
PURPOSE
EOBRRno Compute radiation reaction with PN-Taylor flux.
SYNOPSIS
function [Fphi, Frstar] = EOBRRPN(nu, dydt, y, EOBopt, EOBmet, EOBHam)
DESCRIPTION
EOBRRno Compute radiation reaction with PN-Taylor flux.
   [Fphi, Frstar] = EOBRRPN(nu, dydt, y, EOBopt, EOBmet, EOBHam)
CROSS-REFERENCE INFORMATION
This function calls:
EOBFluxTaylor EOBFluxTaylor.m Compute the Taylor expanded GW flux at 3.5PN order for
This function is called by:
EOBRun
EOBRun_DIN_mod
EOBRun_insplunge_ringdown
SOURCE CODE
function [Fphi, Frstar] = EOBRRPN(nu, dydt, y, EOBopt, EOBmet, EOBHam)
%EOBRRno Compute radiation reaction with PN-Taylor flux.
%
%   [Fphi, Frstar] = EOBRRPN(nu, dydt, y, EOBopt, EOBmet, EOBHam)
%
Omega   = dydt(1);
Omegao3 = Omega.^(1/3);
hatF    = EOBFluxTaylor(nu,Omegao3);
Fphi    = - 32.d0/5.d0 * nu * Omegao3.^7 .* hatF;
Frstar  = 0;