Description of FindMax
Home > EOB > FindMax.m
FindMax
PURPOSE
FindMax Compute extremum of f(x)
SYNOPSIS
function [xm,fm,dfm] = FindMax(x,f,n)
DESCRIPTION
FindMax Compute extremum of f(x)
   [xm,fm,dfm] = findmax(x,f,n) given a function f(x) tabulated at points
   x, return the extremum ( f'=0 ) of the fitting polynomial of degree n
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EOBNQCabFind EOBNQCabFind Compute a's and b's
EOBRun
EOBRun_DIN_mod
EOBRun_insplunge_ringdown
EOBhlmQNMMatch EOBhlmQNMMatch Perform the matching to QNM multipolar wave.
EOBhlmQNMMatch_no_dpsilm EOBhlmQNMMatch Perform the matching to QNM multipolar wave.
SOURCE CODE
function [xm,fm,dfm] = FindMax(x,f,n)
%FindMax Compute extremum of f(x)
%
%   [xm,fm,dfm] = findmax(x,f,n) given a function f(x) tabulated at points
%   x, return the extremum (f'=0) of the fitting polynomial of degree n
%
f = reshape(f,size(x));
[p,s,mu] = polyfit(x,f,n);
dp       = polyder(p);
[xm,dfm] = fzero(@(x) polyval(dp,x,s,mu),(x(end)-x(1))/2);
fm       = polyval(p,xm,s,mu);