Description of LagInt1d
Home > EOB > LagInt1d.m
LagInt1d
PURPOSE
LAGINT1D Lagrangian interpolation routine of 1d data
SYNOPSIS
This is a script file.
DESCRIPTION
LAGINT1D Lagrangian interpolation routine of 1d data
   yi = LagInt1d( p, x, y, xi ) return the Lagrangian interpolating
   polynomial of order p of the function y(x) at points xi
   mex-file: Lagrange1DIntMex.c
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EOBNQCabFind EOBNQCabFind Compute a's and b's
EOBQNMKerrFit EOBQNMKerrFit Fit to the perturbative QNM sigma's.
EOBRun
EOBRun_DIN_mod
EOBRun_insplunge_ringdown
EOBhlmQNMMatch EOBhlmQNMMatch Perform the matching to QNM multipolar wave.
EOBhlmQNMMatch_no_dpsilm EOBhlmQNMMatch Perform the matching to QNM multipolar wave.
compilemex matlab script to compile mex-files
SOURCE CODE
%LAGINT1D Lagrangian interpolation routine of 1d data
%
%   yi = LagInt1d(p, x, y, xi) return the Lagrangian interpolating
%   polynomial of order p of the function y(x) at points xi
%
%   mex-file: Lagrange1DIntMex.c
%