Description of Multipidx
Home > EOB > Multipidx.m
Multipidx
PURPOSE
MULTIPIDX Compute maps between multipolar indexes.
SYNOPSIS
function [LM2K, L,M] = Multipidx(lmax)
DESCRIPTION
MULTIPIDX Compute maps between multipolar indexes.
   [LM2K, L,M] = Multipidx(lmax) return sparse matrix LM2K mapping
   (l,m)->k, and vectors L,M mapping k->l,m
   NOTE: Consider only multipoles m>0.
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EOBRun
EOBRun_DIN_mod
EOBRun_insplunge_ringdown
Example_DIN_mod Main example of EOB run
Example_EOBRunq1 Main example of EOB run
Example_EOBRunq1_insplunge_ringdown Main example of EOB run
Example_NQCdetermine Example of EOB run: determine NQC corrections
Example_Particle Example of EOB run: test-mass case
SOURCE CODE
function [LM2K, L,M] = Multipidx(lmax)
%MULTIPIDX Compute maps between multipolar indexes.
%
%   [LM2K, L,M] = Multipidx(lmax) return sparse matrix LM2K mapping
%   (l,m)->k, and vectors L,M mapping k->l,m
%
%   NOTE: Consider only multipoles m>0.
%
k = 0;
for l=2:lmax
    for m=1:l
        k = k + 1;
        % map (l,m)->k
        LM2K(l,m) = k;
        % map k->l,m
        L(k) = l;
        M(k) = m;
    end
end
LM2K = sparse(LM2K);