Description of SetVOutput
Home > EOB > SetVOutput.m
SetVOutput
PURPOSE
SetVOutput Manage variables in output.
SYNOPSIS
function vout = SetVOutput(n, varargin)
DESCRIPTION
SetVOutput Manage variables in output.
   vout = SetVOutput( n, A,B,C,... ) return a structure with fields
   A,B,C,... if n=1, a cell array {A,B,C,...} otherwise
CROSS-REFERENCE INFORMATION
This function calls:
This function is called by:
EOBExtractAPO EOBExtractAPO Compute amplitude, phase and frequency of waveform.
EOBHam EOBHam Computes the EOB real and effective Hamiltonian for EOB dynamics
EOBHam0 EOBHam0 Computes the EOB real and effective Hamiltonian for particle
EOBMetric EOBMetric Computes the EOB metric potentials and derivatives.
EOBNQCn EOBNQCn Compute n's quantities for NQC.
EOBRun
EOBRun_DIN_mod
EOBRun_insplunge_ringdown
EOBhlm EOBhlm Compute the multipolar resummed waveform.
EOBhlmQNMMatch EOBhlmQNMMatch Perform the matching to QNM multipolar wave.
EOBhlmQNMMatch_no_dpsilm EOBhlmQNMMatch Perform the matching to QNM multipolar wave.
T4Run T4Run Taylor-T4 approximant.
T4Wav T4Wav Taylor-T4 waveform at 2.5 or 3.0 PN accuracy.
SOURCE CODE
function vout = SetVOutput(n, varargin)
%SetVOutput Manage variables in output.
%
%   vout = SetVOutput(n, A,B,C,...) return a structure with fields
%   A,B,C,... if n=1, a cell array {A,B,C,...} otherwise
%
na = length(varargin);
if na<2
    error('At least a variable is required.')
end
if n==1
    MyS = struct();
    for k=1:na
        MyS.(inputname(k+1)) = varargin{k};
    end
    vout = {MyS};
    return;
end
vout = varargin;