% Example of EOB run: test-mass case


% 1. Choose input parameters (these are needed!)

% mass ratio (for RR)
nu = 1e-3;

% a_i's for radiation reaction 
a1 =  0;
a2 =  0;
a3 =  0;
a4 =  0;
% Remark: each a_i i = 1...4 can contain all the multipoles so, here below,
% the order matters ! A quick way to get the correct index without thinking
% is to use the Multipidx.m function. As an example in the following we
% pass the 22 mode only:
LM2K = Multipidx(2);
ainput{1} = zeros(1,length(LM2K)); 
ainput{2} = zeros(1,length(LM2K)); 
ainput{3} = zeros(1,length(LM2K)); 
ainput{4} = zeros(1,length(LM2K)); 
ainput{1}(LM2K(2,2)) = a1;
ainput{2}(LM2K(2,2)) = a2;
ainput{3}(LM2K(2,2)) = a3;
ainput{4}(LM2K(2,2)) = a4;

ainput{5} = 0; 
ainput{6} = 0; 

r0   = 7;     % Initial radius
tmax = 10000; % Final time

dt      = 0.7;   % Width of the matching comb
nQNM    = [5 0]; % no QNM [ positive negative ]
lmaxQNM = 4;  % lmax for QNM matching


% 2. Choose optional input

options = []; % Set options in this struct (see EOBSet.m)

options = EOBSet('Dynamics','particle',...
    'ddotrMethodDyn','noflux',... 
    'ddotrMethodWav','fd',...
    'HorizonFlux','no',...
    'RadialFlux','no',...
    'DetermineNQCab','no',...
    'ODEEventFunRmin',2.001);

% Reminder of all default options
%{
options =EOBSet('Dynamics','eob',...
    'RadReac','din',...
    'ddotrMethodDyn','noflux',...
    'ddotrMethodWav','noflux',...
    'HorizonFlux','yes',...
    'RadialFlux','yes',...
    'FIterms','yes',...
    'rholmarg','v_phi',...
    'PNorder','5pnlog',...
    'resumD','pade03',...
    'resumf22','no',...
    'Tidal','no',...
    'PNTidal','nnlo',...
    'NewtonWaves','no',...
    'DetermineNQCab','no',...
    'NQCFileNR','./DataNR/NRpts4NQC.dat',...
    'QNMDataDir','./dataQNMs/',....
    'textend',100,...
    'ODEEventFunRmin',1.0,...
    'ODESolverRelTol',1e-9,...
    'ODESolverAbsTol',1e-12,...
    'ODESolverRefine',1);
%}


modus   = 3; % (1=> inspl) (2=> inspl+mrg) (3=> inspl+mrg+rng)
verbose = 2; % 0 = minimum, 1 = text ,2 = text+figs
saveme  = 1; % save data ?
outputdir = './tmp';


% 3. Get down to work 

out = EOBRun(nu, ainput, r0,tmax,dt, nQNM,lmaxQNM, ...
    ... the following pars are optional 
    options,... 
    modus,...
    verbose, ...
    saveme, ...
    'tmp')
 

